import { promises as fs } from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { describe, expect, it } from 'vitest'
import { detectDrift, hashContent, splitManaged, writeOutputs } from '../src/writer.js'

/** Mirrors what the writer emits, so the tests exercise the real marker format. */
function managedFile(content: string, opts: { userBefore?: string; userAfter?: string } = {}): string {
  const hash = hashContent(content)
  return (
    (opts.userBefore ?? '') +
    `<!-- ctxmux:begin ctxmux:hash=${hash} — generated by contextmux, do not edit inside this block -->` +
    `\n\n${content.trim()}\n\n` +
    `<!-- ctxmux:end -->` +
    (opts.userAfter ?? '')
  )
}

describe('splitManaged', () => {
  it('finds a managed block whose begin marker carries a hash and a note', () => {
    // This is the regression that matters: an exact-string lookup misses the real marker,
    // the writer concludes there is no block, and every sync duplicates the whole file.
    const file = managedFile('generated content')
    const parts = splitManaged(file, 'CLAUDE.md')
    expect(parts.managed).not.toBeNull()
    expect(parts.managed).toContain('generated content')
  })

  it('preserves user content on both sides of the block', () => {
    const file = managedFile('gen', { userBefore: '# Mine\n\n', userAfter: '\n\n## Also mine\n' })
    const parts = splitManaged(file, 'CLAUDE.md')
    expect(parts.before).toBe('# Mine\n\n')
    expect(parts.after).toBe('\n\n## Also mine\n')
  })

  it('reports no block when there is none', () => {
    const parts = splitManaged('just a normal file', 'CLAUDE.md')
    expect(parts.managed).toBeNull()
    expect(parts.before).toBe('just a normal file')
  })

  it('handles line-comment syntax', () => {
    const file = `# ctxmux:begin ctxmux:hash=abc123456789\nkey = 1\n# ctxmux:end\n`
    const parts = splitManaged(file, 'config.toml')
    expect(parts.managed).toContain('key = 1')
  })
})

describe('detectDrift', () => {
  it('reports no drift for an untouched managed block', () => {
    expect(detectDrift(managedFile('hello'), 'CLAUDE.md', 'block')).toBe(false)
  })

  it('detects an edit inside the managed block', () => {
    const file = managedFile('hello').replace('hello', 'hello, tampered')
    expect(detectDrift(file, 'CLAUDE.md', 'block')).toBe(true)
  })

  it('ignores edits outside the managed block', () => {
    const file = managedFile('hello', { userAfter: '\n\nUser notes added later.\n' })
    expect(detectDrift(file, 'CLAUDE.md', 'block')).toBe(false)
  })

  it('detects an edit to a fully-owned file', () => {
    const content = 'generated body'
    const file = `<!-- Generated by contextmux from .ctxmux/ — do not edit by hand. ctxmux:hash=${hashContent(content)} -->\n\n${content}`
    expect(detectDrift(file, 'x.md', 'full')).toBe(false)
    expect(detectDrift(file.replace('generated body', 'edited body'), 'x.md', 'full')).toBe(true)
  })

  it('returns null when there is no provenance to compare against', () => {
    expect(detectDrift('no header here', 'x.md', 'full')).toBeNull()
  })

  it('does not treat a stripped trailing newline as drift', () => {
    // Editors do this routinely; flagging it would make drift detection cry wolf.
    expect(detectDrift(managedFile('hello').trimEnd(), 'CLAUDE.md', 'block')).toBe(false)
  })
})

describe('drift versus legitimate update', () => {
  it('does not flag a block file as drifted when only the canonical source changed', () => {
    // Regression: the managed region is stored padded with blank lines, so hashing it without
    // trimming both ends never matches. Every ordinary `ctxmux sync` after editing .ctxmux/
    // was reported as a hand edit and refused.
    const onDisk = managedFile('old generated content', { userAfter: '\n\nUser notes.\n' })
    expect(detectDrift(onDisk, 'CLAUDE.md', 'block')).toBe(false)
  })
})

describe('write boundary', () => {
  it('refuses an output path that resolves outside the repository', async () => {
    /*
     * The last line of defence, and the one worth being certain about: every generated file
     * passes through here, whichever compiler produced it and whatever user data steered it.
     */
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      await expect(
        writeOutputs(
          [{ path: '../escaped/AGENTS.md', content: 'x', ownership: 'full', target: 'codex' }],
          { root: dir },
        ),
      ).rejects.toThrow(/outside the repository/)

      await expect(
        writeOutputs(
          [{ path: '/tmp/absolute/AGENTS.md', content: 'x', ownership: 'full', target: 'codex' }],
          { root: dir },
        ),
      ).rejects.toThrow(/outside the repository/)
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })

  it('still writes an ordinary nested path', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      const records = await writeOutputs(
        [{ path: 'src/api/AGENTS.md', content: 'scoped', ownership: 'full', target: 'codex' }],
        { root: dir },
      )
      expect(records[0]?.status).toBe('created')
      expect(await fs.readFile(path.join(dir, 'src/api/AGENTS.md'), 'utf8')).toContain('scoped')
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })
})

describe('files contextmux did not write', () => {
  const file = (over: Record<string, unknown> = {}) => ({
    path: 'out.md',
    content: 'generated',
    ownership: 'full' as const,
    target: 'claude',
    ...over,
  })

  it('does not replace a fully-owned file that carries no provenance', async () => {
    /*
     * `detectDrift` returns null when there is nothing to compare against, and that fell
     * straight through to an overwrite. Absent provenance is the strongest evidence there is
     * that we did not write something, so it counts as a hand edit rather than as permission.
     */
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      await fs.writeFile(path.join(dir, 'out.md'), 'mine\n', 'utf8')

      const records = await writeOutputs([file()], { root: dir })

      expect(records[0]?.status).toBe('drift')
      expect(await fs.readFile(path.join(dir, 'out.md'), 'utf8')).toBe('mine\n')
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })

  it('replaces it when forced, and says that is what happened', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      await fs.writeFile(path.join(dir, 'out.md'), 'mine\n', 'utf8')

      const records = await writeOutputs([file()], { root: dir, force: true })

      expect(records[0]?.status).toBe('forced')
      expect(await fs.readFile(path.join(dir, 'out.md'), 'utf8')).toContain('generated')
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })

  it('still merges into a co-owned file, which is what block ownership is for', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      await fs.writeFile(path.join(dir, 'out.md'), 'mine\n', 'utf8')

      const records = await writeOutputs([file({ ownership: 'block' })], { root: dir })
      const after = await fs.readFile(path.join(dir, 'out.md'), 'utf8')

      expect(records[0]?.status).toBe('updated')
      expect(after).toContain('mine')
      expect(after).toContain('generated')
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })

  it('writes freely when provenance is switched off, since drift cannot be detected anyway', async () => {
    // Turning provenance off is an explicit opt-out. Refusing every write afterwards would make
    // the setting useless rather than permissive.
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-writer-'))
    try {
      await fs.writeFile(path.join(dir, 'out.md'), 'mine\n', 'utf8')

      const records = await writeOutputs([file()], { root: dir, provenance: false })

      expect(records[0]?.status).toBe('updated')
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  })
})

describe('compiling back over the file the content was imported from', () => {
  const block = (over: Record<string, unknown> = {}) => ({
    path: '.github/copilot-instructions.md',
    content: '# House rules\n\nReuse existing helpers before writing new ones.\n',
    ownership: 'block' as const,
    target: 'copilot' as const,
    ...over,
  })

  const withDir = async (fn: (dir: string) => Promise<void>) => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ctxmux-roundtrip-'))
    try {
      await fn(dir)
    } finally {
      await fs.rm(dir, { recursive: true, force: true })
    }
  }

  it('does not write the content twice', async () => {
    /*
     * `ctxmux import` reads an existing instructions file into `.ctxmux/`, and the first `sync`
     * compiles it straight back to the same path. Treating the file's contents as "what the
     * user wrote" put them below a managed block holding the identical text — on a real
     * repository a 779-line file became 1562 lines, and the agent read every instruction twice.
     * Importing an existing repository and compiling it is the first thing anyone does.
     */
    await withDir(async (dir) => {
      const file = block()
      const abs = path.join(dir, file.path)
      await fs.mkdir(path.dirname(abs), { recursive: true })
      await fs.writeFile(abs, file.content, 'utf8')

      await writeOutputs([file], { root: dir })

      const written = await fs.readFile(abs, 'utf8')
      expect(written.match(/House rules/g)).toHaveLength(1)
      expect(written.match(/Reuse existing helpers/g)).toHaveLength(1)
      expect(written).toContain('ctxmux:begin')
    })
  })

  it('still keeps content the user actually wrote', async () => {
    // The guarantee that must not be traded away for the fix above: anything that is not
    // demonstrably a copy of the generated block survives.
    await withDir(async (dir) => {
      const file = block()
      const abs = path.join(dir, file.path)
      await fs.mkdir(path.dirname(abs), { recursive: true })
      await fs.writeFile(abs, '# Notes I wrote by hand\n\nDo not lose this.\n', 'utf8')

      await writeOutputs([file], { root: dir })

      const written = await fs.readFile(abs, 'utf8')
      expect(written).toContain('Do not lose this.')
      expect(written).toContain('Reuse existing helpers')
    })
  })

  it('keeps a file that merely overlaps the generated content', async () => {
    // Only an exact match is collapsed. A partial overlap is not proof the text came from
    // here, and duplicated guidance is a cheaper mistake than deleted guidance.
    await withDir(async (dir) => {
      const file = block()
      const abs = path.join(dir, file.path)
      await fs.mkdir(path.dirname(abs), { recursive: true })
      await fs.writeFile(abs, `${file.content}\n## And one more thing\n\nMine.\n`, 'utf8')

      const written = await (async () => {
        await writeOutputs([file], { root: dir })
        return fs.readFile(abs, 'utf8')
      })()
      expect(written).toContain('Mine.')
    })
  })

  it('ignores blank-line and trailing-space differences', async () => {
    // The question is "did this come from here", not "is this byte-identical".
    await withDir(async (dir) => {
      const file = block()
      const abs = path.join(dir, file.path)
      await fs.mkdir(path.dirname(abs), { recursive: true })
      await fs.writeFile(abs, '\n# House rules   \n\n\nReuse existing helpers before writing new ones.  \n\n', 'utf8')

      await writeOutputs([file], { root: dir })

      expect((await fs.readFile(abs, 'utf8')).match(/House rules/g)).toHaveLength(1)
    })
  })

  it('is stable when run again', async () => {
    await withDir(async (dir) => {
      const file = block()
      const abs = path.join(dir, file.path)
      await fs.mkdir(path.dirname(abs), { recursive: true })
      await fs.writeFile(abs, file.content, 'utf8')

      await writeOutputs([file], { root: dir })
      const once = await fs.readFile(abs, 'utf8')
      await writeOutputs([file], { root: dir })
      const twice = await fs.readFile(abs, 'utf8')

      expect(twice).toBe(once)
    })
  })
})
