/**
 * Scaffolding the GitHub workflows.
 *
 * These used to be two example files you copied out of the repository and edited. That is the
 * friction `init` exists to remove, and it also handed people a file that looked configured and
 * was not: `allow: 'src/**'` and a JQL matching a label nobody uses. Worse, copies drift — the
 * Action gained `share-state` and `args`, and every copy taken before that has a review half
 * that silently does nothing.
 *
 * So they are generated from what was detected, and generated **inert**: the kill switch is off
 * until somebody sets a repository variable. That makes the file a proposal sitting in a diff,
 * which is what `init` already writes for rules and skills — not something that starts acting
 * the moment it lands.
 *
 * Scaffolded once, never managed. `sync` refuses to clobber your edits to `CLAUDE.md`; a file
 * carrying repository write permissions and a token deserves more caution than that, not less,
 * so nothing here ever rewrites one that already exists.
 */
import type { ProjectProfile } from '@contextmux/repo'

/** Marker the doctor reads to tell which version of the Action a workflow was written for. */
export const WORKFLOW_MARKER = 'ctxmux:workflow'

/** Features a scaffolded workflow is expected to carry, so drift can be reported. */
export const WORKFLOW_FEATURES = ['share-state'] as const

export interface WorkflowFile {
  path: string
  content: string
}

export interface WorkflowContext {
  profile: ProjectProfile
  /** Which tracker resolved: file, github or jira. */
  tracker: string
  /** Whether a git remote exists — without one there is nothing to scaffold for. */
  hasRemote: boolean
}

/**
 * Paths an agent may modify, from the layout rather than a guess.
 *
 * A workspace root is the honest answer in a monorepo: `src/**` describes almost no real
 * repository, and a scope that matches nothing rejects every change the agent makes.
 */
export function allowGlobs(profile: ProjectProfile): string[] {
  if (profile.isMonorepo && profile.workspaces.length > 0) {
    const roots = new Set(profile.workspaces.map((w) => w.dir.split('/')[0]).filter(Boolean))
    if (roots.size > 0) return [...roots].sort().map((r) => `${r}/**`)
  }
  return ['src/**', 'test/**']
}

function header(name: string): string {
  return [
    `# ${name}`,
    `#`,
    `# Generated by contextmux (${WORKFLOW_MARKER}). Yours to edit — nothing regenerates it.`,
    `#`,
    `# This does nothing until you set the repository variable CTXMUX_ENABLED to true.`,
    `# Settings -> Secrets and variables -> Actions -> Variables.`,
  ].join('\n')
}

function secretsFor(tracker: string): string[] {
  const secrets = ['CTXMUX_TOKEN']
  if (tracker === 'jira') secrets.push('JIRA_URL', 'JIRA_EMAIL', 'JIRA_API_TOKEN')
  return secrets
}

function runWorkflow(ctx: WorkflowContext): string {
  const allow = allowGlobs(ctx.profile).join(',')
  const jira = ctx.tracker === 'jira'

  return `${header('Drive tasks to pull requests, under gates')}

name: contextmux run

on:
  workflow_dispatch:
    inputs:
      task:
        description: '${jira ? 'Ticket key' : 'Task id'}. Leave empty to take the next eligible one.'
        required: false
  # Uncomment to pick work up on a schedule, once you trust it.
  # schedule:
  #   - cron: '0 */2 * * 1-5'

concurrency:
  # Serialise, so two runs cannot pick up the same task.
  group: ctxmux-\${{ inputs.task || 'batch' }}
  cancel-in-progress: false

permissions:
  # write, because run state is pushed to a branch of its own — see share-state below.
  contents: write
  issues: write
  pull-requests: write

jobs:
  run:
    # A kill switch that does not require editing this file to use.
    if: vars.CTXMUX_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7

      - uses: contextmux/contextmux/packages/action@v0
        with:
          command: run
          task: \${{ inputs.task }}
          tracker: ${ctx.tracker}
          # copilot delegates to GitHub's cloud agent, which opens its own pull request. A
          # driven agent (claude) works in a worktree on this runner instead, so it needs
          # \`--open-pr\` below — without it the runner is destroyed with the work still on it.
          agent: copilot
          # Detected from this repository's layout. Narrow it further if a task should not
          # reach all of these.
          allow: '${allow}'
          max-rounds: '2'
          # Only meaningful for a driven agent; copilot has already opened one by this point,
          # and the flag is ignored because there is no local branch to push.
          args: '--open-pr'
          # Publishes what this run recorded, so the review workflow can find it. Without it,
          # that workflow runs in a fresh checkout, finds nothing, and the feedback reaches
          # nobody.
          share-state: 'true'
          github-token: \${{ secrets.CTXMUX_TOKEN }}${
            jira
              ? `
          jira-url: \${{ secrets.JIRA_URL }}
          jira-email: \${{ secrets.JIRA_EMAIL }}
          jira-token: \${{ secrets.JIRA_API_TOKEN }}`
              : ''
          }
`
}

function reviewWorkflow(ctx: WorkflowContext): string {
  return `${header('Feed review feedback back to the agent')}
#
# Separate from the run workflow on purpose: picking up work and reacting to a review are
# different triggers with different permissions, and combining them gives the review path
# write access it does not need.

name: contextmux review

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  review:
    if: vars.CTXMUX_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7

      - uses: contextmux/contextmux/packages/action@v0
        with:
          command: event
          tracker: ${ctx.tracker}
          # Fetches the state the run workflow published. This is the whole reason this
          # workflow can find the run it is meant to be advancing.
          share-state: 'true'
          github-token: \${{ secrets.CTXMUX_TOKEN }}
`
}

/** The workflows to scaffold. Empty when there is no remote to run them against. */
export function workflowFiles(ctx: WorkflowContext): WorkflowFile[] {
  if (!ctx.hasRemote) return []
  return [
    { path: '.github/workflows/ctxmux-run.yml', content: runWorkflow(ctx) },
    { path: '.github/workflows/ctxmux-review.yml', content: reviewWorkflow(ctx) },
  ]
}

/** What still has to be true before a scaffolded workflow can do anything. */
export function remainingSetup(ctx: WorkflowContext): string[] {
  const todo = secretsFor(ctx.tracker).map((s) => `${s} is not set as a repository secret`)
  todo.push('the Copilot coding agent is not enabled on this repository')
  todo.push("CTXMUX_ENABLED is unset, so nothing runs — set it to 'true' when you are ready")
  return todo
}
