/**
 * Scaffolding the GitHub workflows.
 *
 * These used to be two example files you copied out of the repository and edited. That is the
 * friction `init` exists to remove, and it also handed people a file that looked configured and
 * was not: `allow: 'src/**'` and a JQL matching a label nobody uses. Worse, copies drift — the
 * Action gained `share-state` and `args`, and every copy taken before that has a review half
 * that silently does nothing.
 *
 * So they are generated from what was detected, and generated **inert**: the kill switch is off
 * until somebody sets a repository variable. That makes the file a proposal sitting in a diff,
 * which is what `init` already writes for rules and skills — not something that starts acting
 * the moment it lands.
 *
 * Scaffolded once, never managed. `sync` refuses to clobber your edits to `CLAUDE.md`; a file
 * carrying repository write permissions and a token deserves more caution than that, not less,
 * so nothing here ever rewrites one that already exists.
 */
import type { ProjectProfile } from '@contextmux/repo'

/** Marker the doctor reads to tell which version of the Action a workflow was written for. */
export const WORKFLOW_MARKER = 'ctxmux:workflow'

/** Features a scaffolded workflow is expected to carry, so drift can be reported. */
export const WORKFLOW_FEATURES = ['share-state'] as const

export interface WorkflowFile {
  path: string
  content: string
}

export interface WorkflowContext {
  profile: ProjectProfile
  /** Which tracker resolved: file, github or jira. */
  tracker: string
  /** Whether a git remote exists — without one there is nothing to scaffold for. */
  hasRemote: boolean
  /** Which agent will run tasks: claude, copilot, cursor, codex or local. */
  agent?: string
}

/**
 * Paths an agent may modify, from the layout rather than a guess.
 *
 * A workspace root is the honest answer in a monorepo: `src/**` describes almost no real
 * repository, and a scope that matches nothing rejects every change the agent makes.
 */
export function allowGlobs(profile: ProjectProfile): string[] {
  if (profile.isMonorepo && profile.workspaces.length > 0) {
    const roots = new Set(profile.workspaces.map((w) => w.dir.split('/')[0]).filter(Boolean))
    if (roots.size > 0) return [...roots].sort().map((r) => `${r}/**`)
  }
  return ['src/**', 'test/**']
}

/**
 * `gated: false` drops the kill-switch lines.
 *
 * They exist because `run` and `review` spend money and write to the repository the moment
 * they fire — a proposal sitting in a diff, not something already running. `check` does
 * neither: it reads `.ctxmux/`, compares it to what is on disk, and reports. There is nothing
 * to opt into, and gating it behind a variable would only mean the one workflow that can never
 * do harm is also the one that silently does nothing until somebody remembers to flip it on.
 */
function header(name: string, opts: { gated?: boolean } = {}): string {
  const gated = opts.gated ?? true
  return [
    `# ${name}`,
    `#`,
    `# Generated by contextmux (${WORKFLOW_MARKER}). Yours to edit — nothing regenerates it.`,
    ...(gated
      ? [
          `#`,
          `# This does nothing until you set the repository variable CTXMUX_ENABLED to true.`,
          `# Settings -> Secrets and variables -> Actions -> Variables.`,
        ]
      : []),
  ].join('\n')
}

function secretsFor(tracker: string): string[] {
  const secrets = ['CTXMUX_TOKEN']
  if (tracker === 'jira') secrets.push('JIRA_URL', 'JIRA_EMAIL', 'JIRA_API_TOKEN')
  return secrets
}

function runWorkflow(ctx: WorkflowContext): string {
  const allow = allowGlobs(ctx.profile).join(',')
  const jira = ctx.tracker === 'jira'

  return `${header('Drive tasks to pull requests, under gates')}

name: contextmux run

on:
  workflow_dispatch:
    inputs:
      task:
        description: '${jira ? 'Ticket key' : 'Task id'}. Leave empty to take the next eligible one.'
        required: false
  # Uncomment to pick work up on a schedule, once you trust it.
  # schedule:
  #   - cron: '0 */2 * * 1-5'

concurrency:
  # Serialise, so two runs cannot pick up the same task.
  group: ctxmux-\${{ inputs.task || 'batch' }}
  cancel-in-progress: false

permissions:
  # write, because run state is pushed to a branch of its own — see share-state below.
  contents: write
  issues: write
  pull-requests: write

jobs:
  run:
    # A kill switch that does not require editing this file to use.
    if: vars.CTXMUX_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7

      - uses: contextmux/contextmux/packages/action@v0
        with:
          command: run
          task: \${{ inputs.task }}
          tracker: ${ctx.tracker}
          # copilot delegates to GitHub's cloud agent, which opens its own pull request. A
          # driven agent (claude) works in a worktree on this runner instead, so it needs
          # \`--open-pr\` below — without it the runner is destroyed with the work still on it.
          agent: ${ctx.agent ?? 'copilot'}
          # Detected from this repository's layout. Narrow it further if a task should not
          # reach all of these.
          allow: '${allow}'
          max-rounds: '2'
          # Only meaningful for a driven agent; copilot has already opened one by this point,
          # and the flag is ignored because there is no local branch to push.
          args: '--open-pr'
          # Publishes what this run recorded, so the review workflow can find it. Without it,
          # that workflow runs in a fresh checkout, finds nothing, and the feedback reaches
          # nobody.
          share-state: 'true'
          github-token: \${{ secrets.CTXMUX_TOKEN }}${
            jira
              ? `
          jira-url: \${{ secrets.JIRA_URL }}
          jira-email: \${{ secrets.JIRA_EMAIL }}
          jira-token: \${{ secrets.JIRA_API_TOKEN }}`
              : ''
          }
`
}

function reviewWorkflow(ctx: WorkflowContext): string {
  return `${header('Feed review feedback back to the agent')}
#
# Separate from the run workflow on purpose: picking up work and reacting to a review are
# different triggers with different permissions, and combining them gives the review path
# write access it does not need.

name: contextmux review

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  review:
    if: vars.CTXMUX_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7

      - uses: contextmux/contextmux/packages/action@v0
        with:
          command: event
          tracker: ${ctx.tracker}
          # Fetches the state the run workflow published. This is the whole reason this
          # workflow can find the run it is meant to be advancing.
          share-state: 'true'
          github-token: \${{ secrets.CTXMUX_TOKEN }}
`
}

function checkWorkflow(): string {
  return `${header('Verify .ctxmux/ compiles without drift', { gated: false })}
#
# Catches two things a review otherwise has to notice by eye: a generated file — CLAUDE.md,
# .cursor/rules/*, the Copilot instructions — edited by hand instead of through .ctxmux/, and
# .ctxmux/ changing without anyone running \`ctxmux sync\` and committing the result. Needs no
# secrets: it never leaves this checkout.

name: contextmux check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: contextmux/contextmux/packages/action@v0
        with:
          command: check
          args: --strict
`
}

/** The workflows to scaffold. Empty when there is no remote to run them against. */
export function workflowFiles(ctx: WorkflowContext): WorkflowFile[] {
  if (!ctx.hasRemote) return []
  return [
    { path: '.github/workflows/ctxmux-run.yml', content: runWorkflow(ctx) },
    { path: '.github/workflows/ctxmux-review.yml', content: reviewWorkflow(ctx) },
    { path: '.github/workflows/ctxmux-check.yml', content: checkWorkflow() },
  ]
}

/** One thing that has to be true before a scaffolded workflow can do anything. */
export interface SetupStep {
  /** What it is, in a sentence, for somebody who has not seen the name before. */
  what: string
  /** The command that sets it, or instructions when there is no command. */
  how: string
  /** Whether it is already done. Undefined when it could not be checked. */
  done?: boolean
}

/**
 * What still has to be true before a scaffolded workflow can do anything.
 *
 * Each step says what the thing is and how to set it. A list of bare names — `CTXMUX_TOKEN is
 * not set` — tells somebody who has never seen that name nothing they can act on, and this list
 * is the first time most people meet any of them.
 *
 * It also used to assert "is not set" without looking, which was wrong every time somebody had
 * already set it. Now it checks where it can and says nothing it has not verified.
 */
export function remainingSetup(ctx: WorkflowContext, known: Set<string> = new Set()): SetupStep[] {
  const steps: SetupStep[] = [
    {
      what:
        'CTXMUX_TOKEN — a GitHub token contextmux uses to open pull requests, comment, and push ' +
        'run state. It cannot be the built-in GITHUB_TOKEN: GitHub refuses to start a workflow ' +
        'from an event that token created, so the review half of the loop would never fire.',
      // `gh secret set` prompts for a value; it does not mint one. Saying only "set this
      // secret" leaves somebody at a prompt with nothing to paste, which is the same gap this
      // whole list exists to close.
      how:
        'gh auth token | gh secret set CTXMUX_TOKEN    # quick: reuses your gh login, but that is full account access\n' +
        '    Scoped instead: github.com > Settings > Developer settings > Fine-grained tokens.\n' +
        '    This repository only, with Contents, Issues and Pull requests set to read and write.\n' +
        '    Then: gh secret set CTXMUX_TOKEN  and paste it.',
      done: known.has('CTXMUX_TOKEN'),
    },
  ]

  if (ctx.tracker === 'jira') {
    steps.push(
      {
        what: 'JIRA_URL — your Atlassian site, like https://acme.atlassian.net. Not secret.',
        how: 'gh variable set JIRA_URL --body "https://acme.atlassian.net"',
        done: known.has('JIRA_URL'),
      },
      {
        what: 'JIRA_EMAIL — the account the API token belongs to.',
        how: 'gh secret set JIRA_EMAIL    # prompts; paste the address you sign in to Jira with',
        done: known.has('JIRA_EMAIL'),
      },
      {
        what:
          'JIRA_API_TOKEN — from id.atlassian.com under Security. It carries everything your ' +
          'Jira account can reach, so a service account is safer than your own.',
        how: 'gh secret set JIRA_API_TOKEN    # create it at id.atlassian.com first, then paste',
        done: known.has('JIRA_API_TOKEN'),
      },
    )
  }

  // Only what this repository's agent actually needs. Telling somebody running Claude to enable
  // Copilot is noise in a list they are reading precisely because they do not yet know which
  // parts apply to them.
  if (ctx.agent === 'copilot') {
    steps.push({
      what: 'The Copilot coding agent has to be enabled on this repository before it can be given work.',
      how: 'Repository settings, under Copilot. There is no command for this one.',
    })
  } else if (ctx.agent && ctx.agent !== 'local') {
    steps.push({
      what: `ANTHROPIC_API_KEY — credentials for ${ctx.agent}, which runs on the runner rather than in a vendor's cloud.`,
      how: 'gh secret set ANTHROPIC_API_KEY    # from console.anthropic.com, then paste',
      done: known.has('ANTHROPIC_API_KEY'),
    })
  }

  steps.push({
    what: 'CTXMUX_ENABLED — the kill switch. Every scaffolded workflow checks it, so nothing runs until it is true.',
    how: 'gh variable set CTXMUX_ENABLED --body true',
    done: known.has('CTXMUX_ENABLED'),
  })

  return steps
}
