/**
 * The safe writer.
 *
 * Users editing and improving generated context files is the whole point of this tool, so
 * the writer treats hand edits as sacred. Every generated file carries a provenance header
 * with a hash of the content contextmux produced. On the next sync we recompute that hash: if
 * it still matches, the file is untouched and safe to regenerate; if it does not, a human
 * changed it and we refuse to overwrite without `--force`.
 *
 * `block` ownership exists for files a user legitimately co-owns — `CLAUDE.md`, `AGENTS.md` —
 * where contextmux manages a delimited region and everything outside it is preserved verbatim.
 */
import { createHash } from 'node:crypto'
import { promises as fs } from 'node:fs'
import * as path from 'node:path'
import type { OutputFile } from './compilers/types.js'
import { writeFileAtomic } from './fsx.js'

export const BEGIN = 'ctxmux:begin'
export const END = 'ctxmux:end'

export type WriteStatus =
  | 'created'
  | 'updated'
  | 'unchanged'
  | 'drift' // hand-edited; skipped unless forced
  | 'forced' // hand-edited; overwritten because --force was passed

export interface WriteRecord {
  path: string
  status: WriteStatus
  target: string
}

export interface WriteOptions {
  root: string
  /** Compute results without touching the filesystem. */
  dryRun?: boolean
  /** Overwrite hand-edited generated files. */
  force?: boolean
  /** Emit provenance headers. Disabling makes drift undetectable — `check` will warn. */
  provenance?: boolean
}

export function hashContent(s: string): string {
  return createHash('sha256').update(normalizeForHash(s)).digest('hex').slice(0, 12)
}

/**
 * Canonicalise before hashing.
 *
 * The same logical content appears with different surrounding whitespace depending on where
 * it sits: padded inside a managed block, or separated from a provenance header. Comparing
 * raw text makes every ordinary regeneration look like a hand edit. Line endings, blank-line
 * runs and boundary whitespace are formatting, not content.
 */
function normalizeForHash(s: string): string {
  return s.replace(/\r\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim()
}

/** Remove the provenance line wherever it sits, so the remainder can be compared. */
function stripProvenance(s: string): string {
  return s.replace(/^[^\n]*ctxmux:hash=[0-9a-f]{12}[^\n]*\n?/m, '')
}

function commentSyntax(filePath: string): { open: string; close: string } | null {
  const ext = path.extname(filePath)
  if (ext === '.json') return null // JSON has no comment syntax
  if (ext === '.toml' || ext === '.yaml' || ext === '.yml') return { open: '#', close: '' }
  return { open: '<!--', close: '-->' } // markdown, mdc
}

function provenanceHeader(filePath: string, hash: string): string | null {
  const c = commentSyntax(filePath)
  if (!c) return null
  const text = `Generated by contextmux from .ctxmux/ — do not edit by hand. ctxmux:hash=${hash}`
  return c.close ? `${c.open} ${text} ${c.close}` : `${c.open} ${text}`
}

const HASH_RE = /ctxmux:hash=([0-9a-f]{12})/

function blockMarkers(filePath: string): { begin: string; end: string } {
  const c = commentSyntax(filePath) ?? { open: '<!--', close: '-->' }
  const wrap = (t: string) => (c.close ? `${c.open} ${t} ${c.close}` : `${c.open} ${t}`)
  return { begin: wrap(BEGIN), end: wrap(END) }
}

/**
 * Locate a marker by its tag rather than by exact string match.
 *
 * The begin marker carries a hash and a human-readable note inside the same comment, so an
 * exact-match lookup never finds it. Getting this wrong is quietly catastrophic: the writer
 * concludes there is no managed block, prepends a fresh one, and every sync duplicates the
 * entire file. Match the tag, then expand to the enclosing comment.
 */
function findMarker(
  text: string,
  tag: string,
  filePath: string,
): { start: number; end: number } | null {
  const idx = text.indexOf(tag)
  if (idx === -1) return null
  const c = commentSyntax(filePath) ?? { open: '<!--', close: '-->' }

  if (c.close) {
    const start = text.lastIndexOf(c.open, idx)
    if (start === -1) return null
    const closeAt = text.indexOf(c.close, idx)
    if (closeAt === -1) return null
    return { start, end: closeAt + c.close.length }
  }

  // Line comments: the marker owns its whole line.
  const lineStart = text.lastIndexOf('\n', idx) + 1
  const lineEnd = text.indexOf('\n', idx)
  return { start: lineStart, end: lineEnd === -1 ? text.length : lineEnd }
}

/** Extract the contextmux-managed region and the surrounding user content. */
export function splitManaged(
  existing: string,
  filePath: string,
): { before: string; managed: string | null; after: string } {
  const begin = findMarker(existing, BEGIN, filePath)
  const end = findMarker(existing, END, filePath)
  if (!begin || !end || end.start < begin.end) {
    return { before: existing, managed: null, after: '' }
  }
  return {
    before: existing.slice(0, begin.start),
    managed: existing.slice(begin.end, end.start),
    after: existing.slice(end.end),
  }
}

function renderFull(file: OutputFile, provenance: boolean): string {
  if (!provenance || file.noProvenance) return file.content
  const header = provenanceHeader(file.path, hashContent(file.content))
  if (!header) return file.content

  /*
   * Place the header *after* any YAML frontmatter.
   *
   * Frontmatter is only frontmatter when it opens on line 1. Putting a comment above it turns
   * the block into ordinary text, and every target silently loses the metadata it carries —
   * Copilot's `applyTo` scoping, Cursor's `globs`, a skill's activation `description`. The
   * file still looks correct to a human reader, which is what makes it dangerous.
   */
  const fmEnd = frontmatterEnd(file.content)
  if (fmEnd === null) return `${header}\n\n${file.content}`
  return `${file.content.slice(0, fmEnd)}\n${header}\n${file.content.slice(fmEnd)}`
}

/** Index just past the closing delimiter of a leading frontmatter block, or null. */
function frontmatterEnd(content: string): number | null {
  if (!content.startsWith('---\n')) return null
  const close = content.indexOf('\n---', 3)
  if (close === -1) return null
  const lineEnd = content.indexOf('\n', close + 1)
  return lineEnd === -1 ? content.length : lineEnd + 1
}

function renderBlock(file: OutputFile, existing: string | null, provenance: boolean): string {
  const { end } = blockMarkers(file.path)
  const hash = hashContent(file.content)
  const note = provenance ? ` ctxmux:hash=${hash}` : ''
  const c = commentSyntax(file.path) ?? { open: '<!--', close: '-->' }
  const beginWithHash = c.close
    ? `${c.open} ${BEGIN}${note} — generated by contextmux, do not edit inside this block ${c.close}`
    : `${c.open} ${BEGIN}${note} — generated by contextmux, do not edit inside this block`

  const managedBody = `\n\n${file.content.trim()}\n\n`

  if (existing === null) {
    return `${beginWithHash}${managedBody}${end}\n`
  }
  const parts = splitManaged(existing, file.path)
  if (parts.managed === null) {
    /*
     * The file is the source this content was imported from.
     *
     * `ctxmux import` reads an existing `.github/copilot-instructions.md` into `.ctxmux/`, and
     * the first `sync` compiles it straight back to the same path. Keeping the file's contents
     * as "everything the user wrote" then writes them a second time, below a managed block
     * holding the identical text — a 779-line file becomes 1562 lines, and the agent reads
     * every instruction twice. Importing an existing repository and compiling it is the first
     * thing anyone does, so this is the first thing they saw.
     *
     * Only an exact match is collapsed. Every line dropped here is demonstrably present in the
     * block being written, which makes it lossless; anything less certain keeps the old
     * behaviour, because duplicated guidance is a far cheaper mistake than deleted guidance.
     */
    if (sameBody(existing, file.content)) {
      return `${beginWithHash}${managedBody}${end}\n`
    }
    // File exists but has no managed block — prepend one and keep everything the user wrote.
    return `${beginWithHash}${managedBody}${end}\n\n${existing.trimStart()}`
  }
  return `${parts.before}${beginWithHash}${managedBody}${end}${parts.after}`
}

/**
 * Whether two documents carry the same text, ignoring blank lines and trailing spaces.
 *
 * Deliberately not a byte comparison: a compiler that re-wraps a paragraph or normalises how
 * a file ends still produced the same content, and the question being asked is "did this come
 * from here", not "is this identical".
 */
function sameBody(a: string, b: string): boolean {
  const lines = (text: string) =>
    text
      .split('\n')
      .map((line) => line.trimEnd())
      .filter((line) => line.length > 0)
      .join('\n')
  return lines(a) === lines(b)
}

/**
 * Decide whether the on-disk file still matches what contextmux last generated.
 * Returns null when there is no provenance to compare against.
 */
export function detectDrift(existing: string, filePath: string, ownership: 'full' | 'block'): boolean | null {
  const m = HASH_RE.exec(existing)
  if (!m) return null
  const recorded = m[1]!
  if (ownership === 'block') {
    const { managed } = splitManaged(existing, filePath)
    if (managed === null) return null
    return hashContent(managed) !== recorded
  }
  return hashContent(stripProvenance(existing)) !== recorded
}

async function readIfExists(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw err
  }
}

/** Two compilers claiming the same output path is a bug, not a merge. */
export function findCollisions(files: Array<OutputFile & { target: string }>): string[] {
  const byPath = new Map<string, string[]>()
  for (const f of files) {
    const list = byPath.get(f.path) ?? []
    list.push(f.target)
    byPath.set(f.path, list)
  }
  return [...byPath]
    .filter(([, targets]) => targets.length > 1)
    .map(([p, targets]) => `${p} (claimed by ${targets.join(', ')})`)
}

export async function writeOutputs(
  files: Array<OutputFile & { target: string }>,
  opts: WriteOptions,
): Promise<WriteRecord[]> {
  const provenance = opts.provenance !== false
  const records: WriteRecord[] = []

  const root = path.resolve(opts.root)

  for (const file of files) {
    const abs = path.resolve(root, file.path)

    /*
     * Never write outside the repository we were pointed at.
     *
     * Output paths are partly derived from user data — a rule's globs decide where a nested
     * `AGENTS.md` lands — so a compiler can be steered into naming an absolute path or one
     * that climbs out of the project. The compilers guard their own inputs, but this is the
     * single place every generated file passes through, and it is the one worth being certain
     * about: `sync` is a routine command that people run without reading the output.
     */
    if (abs !== root && !abs.startsWith(root + path.sep)) {
      throw new Error(
        `refusing to write "${file.path}" — it resolves outside the repository (${abs}). ` +
          'A rule or skill glob is naming a location outside the project.',
      )
    }

    const existing = await readIfExists(abs)

    const next =
      file.ownership === 'block'
        ? renderBlock(file, existing, provenance)
        : renderFull(file, provenance)

    if (existing !== null && existing.trimEnd() === next.trimEnd()) {
      records.push({ path: file.path, status: 'unchanged', target: file.target })
      continue
    }

    if (existing !== null) {
      /*
       * A file we did not write is not ours to replace.
       *
       * `detectDrift` returns null when there is no provenance to compare against, and that
       * used to fall straight through to an overwrite — so a hand-written
       * `.github/prompts/deploy.prompt.md` was destroyed the first time a skill happened to be
       * named `deploy`. The report called it an `update`, which is exactly what it looks like
       * when the file *was* ours.
       *
       * Absent provenance is the strongest possible evidence that contextmux did not write
       * something, so it is treated as a hand edit rather than as permission. Block-owned files
       * are exempt: they merge around a managed region and preserve the rest by construction.
       *
       * Only when provenance is switched on. Turning it off is an explicit opt-out of drift
       * detection, and refusing to write every file afterwards would make that setting useless.
       */
      const drifted =
        detectDrift(existing, file.path, file.ownership) ??
        (provenance && file.ownership === 'full')

      if (drifted && !opts.force) {
        records.push({ path: file.path, status: 'drift', target: file.target })
        continue
      }
      if (drifted && opts.force) {
        if (!opts.dryRun) await writeFileAtomic(abs, next)
        records.push({ path: file.path, status: 'forced', target: file.target })
        continue
      }
    }

    if (!opts.dryRun) await writeFileAtomic(abs, next)
    records.push({
      path: file.path,
      status: existing === null ? 'created' : 'updated',
      target: file.target,
    })
  }

  return records
}
